Repository codeit-project-rolling/rolling, pull requests merged in 2024-03, with the labels that each got.

#30 [refactor] Button 컴포넌트 수정
  src/components/Button/Button.jsx
  src/components/Button/Button.module.scss
  src/components/card/card.jsx
  src/pages/HomePage/HomePage.module.scss
  src/pages/PostPage/PostIdPage/PostIdPage.jsx
Labels: 완료

#28 [Feat] axios api
  .gitignore
  package-lock.json
  package.json
  src/apis/apiDelete.js
  src/apis/apiGet.js
  src/apis/apiPost.js
  src/hooks/.gitkeep
  src/hooks/useDeleteMessage.js
  src/hooks/useDeleteRecipient.js
  src/hooks/useGetMessageList.js
  src/hooks/useGetReactionList.js
  src/hooks/useGetRecipient.js
  src/hooks/useGetRecipientList.js
  src/hooks/usePostMessage.js
  src/hooks/usePostReaction.js
  src/hooks/usePostRecipient.js
  src/index.js
  src/pages/.gitkeep
  src/utils/.gitkeep
Labels: ⏳ PR 머지 대기 중

#37 [Feat] Background images api request
  src/apis/.gitkeep
  src/apis/apiDelete.js
  src/apis/apiGet.js
  src/apis/apiPost.js
  src/hooks/useDeleteMessage.js
  src/hooks/useDeleteRecipient.js
  src/hooks/useGetBackgroundImageList.js
  src/hooks/useGetMessageList.js
  src/hooks/useGetReactionList.js
  src/hooks/useGetRecipient.js
  src/hooks/useGetRecipientList.js
  src/hooks/usePostMessage.js
  src/hooks/usePostReaction.js
  src/hooks/usePostRecipient.js
Labels: ⏳ PR 머지 대기 중

#38 Feature axios api
  src/apis/createApiRequest.js
  src/hooks/useDeleteMessage.js
  src/hooks/useDeleteRecipient.js
  src/hooks/useGetBackgroundImageList.js
  src/hooks/useGetMessageList.js
  src/hooks/useGetReactionList.js
  src/hooks/useGetRecipient.js
  src/hooks/useGetRecipientList.js
  src/hooks/usePostMessage.js
  src/hooks/usePostReaction.js
  src/hooks/usePostRecipient.js
Labels: ⏳ PR 머지 대기 중

#32 [Feat] homepage
  src/App.js
  src/assets/images/img-homepage-mobile-service-01.png
  src/assets/images/img-homepage-mobile-service-02.png
  src/assets/images/img-homepage-service-01.png
  src/assets/images/img-homepage-service-02.png
  src/assets/styles/mixin.scss
  src/components/Button/Button.jsx
  src/components/Modal/Modal.jsx
  src/components/Modal/Modal.module.scss
  src/components/ServiceSection/ServiceSection.jsx
  src/components/ServiceSection/ServiceSection.module.scss
  src/pages/HomePage/HomePage.jsx
  src/pages/HomePage/HomePage.module.scss
Labels: ⏳ PR 머지 대기 중

#34 [Feat] modal context
  .eslintrc.js
  README.md
  package-lock.json
  package.json
  public/index.html
  src/components/Modal/Modal.jsx
  src/components/Modal/Modal.module.scss
  src/contexts/ModalComponent.js
  src/contexts/ModalContext.js
  src/contexts/ModalProvider.js
  src/hooks/useModal.js
  src/index.js
Labels: ⏳ PR 머지 대기 중

#36 [Feat] Post페이지 && 헤더 컴포넌트
  src/assets/images/check.svg
  src/components/BackgroundOption/BackColorOption.jsx
  src/components/BackgroundOption/BackColorOption.module.scss
  src/components/BackgroundOption/BackImageOption.jsx
  src/components/BackgroundOption/BackImageOption.module.scss
  src/components/CheckButton/CheckButton.jsx
  src/components/CheckButton/CheckButton.module.scss
  src/components/Header/HeaderComponents/EmojiDropdown.jsx
  src/components/Header/HeaderComponents/EmojiDropdown.module.scss
  src/components/Header/HeaderComponents/Header.jsx
  src/components/Header/HeaderComponents/Header.module.scss
  src/components/Header/HeaderComponents/HeaderService.jsx
  src/components/Header/HeaderComponents/HeaderService.module.scss
  src/components/Header/HeaderComponents/ShareDropdown.module.scss
  src/components/Header/HeaderLayout.jsx
  src/components/Header/HeaderLayout.module.scss
  src/components/Header/mock.json
  src/components/ToggleButton/ToggleButton.jsx
  src/hooks/usePostRecipient.js
  src/pages/PostPage/PostIdPage/PostIdPage.jsx
  src/pages/PostPage/PostPage.jsx
  src/pages/PostPage/PostPage.module.scss
Labels: ⏳ PR 머지 대기 중

#43 [Feat] List Page
  package-lock.json
  package.json
  src/assets/images/arrow_left.svg
  src/assets/images/arrow_right.svg
  src/components/ArrowButton/ArrowButton.module.scss
  src/components/ArrowButton/LeftArrowButton.jsx
  src/components/ArrowButton/RightArrowButton.jsx
  src/components/Slider/CardSlider.jsx
  src/components/Slider/CardSliderStyle.module.scss
  src/components/Slider/Skeleton.jsx
  src/components/card/Card.jsx
  src/components/card/Card.module.scss
  src/components/card/Cardlist.jsx
  src/components/card/Cardlist.module.scss
  src/components/card/cardUtils.js
  src/components/card/dump.data.js
  src/pages/ListPage/ListPage.jsx
  src/pages/ListPage/ListPage.module.scss
  src/pages/PostPage/PostIdPage/EditPage/EditPage.jsx
  src/pages/PostPage/PostIdPage/PostIdPage.jsx
Labels: 💻 개발 중

#46 [Feat] HeaderService 컴포넌트 Emoji post 요청보내기
  package-lock.json
  package.json
  src/components/Header/HeaderComponents/EmojiDropdown.jsx
  src/components/Header/HeaderComponents/EmojiDropdown.module.scss
  src/components/Header/HeaderComponents/Header.module.scss
  src/components/Header/HeaderComponents/HeaderService.jsx
  src/components/Header/HeaderComponents/HeaderService.module.scss
  src/hooks/useGetRecipient.js
  src/hooks/usePostReaction.js
  src/pages/PostPage/PostPage.jsx
Labels: ⏳ PR 머지 대기 중

#51 [Feat] infinite scroll
  package-lock.json
  package.json
  src/apis/createApiRequest.js
  src/components/BadgeEmoji/BadgeEmoji.module.scss
  src/components/Header/HeaderComponents/EmojiDropdown.module.scss
  src/components/Header/HeaderComponents/Header.jsx
  src/components/Header/HeaderComponents/Header.module.scss
  src/components/Header/HeaderComponents/HeaderService.jsx
  src/components/Header/HeaderComponents/HeaderService.module.scss
  src/components/Header/HeaderLayout.jsx
  src/components/Header/HeaderLayout.module.scss
  src/components/Modal/Modal.module.scss
  src/components/card/card.jsx
  src/components/card/card.module.scss
  src/hooks/useGetMessageList.js
  src/hooks/useGetReactionList.js
  src/hooks/useIntersectionObserver.js
  src/pages/HomePage/HomePage.jsx
  src/pages/HomePage/HomePage.module.scss
  src/pages/ListPage/ListPage.jsx
  src/pages/PostPage/PostIdPage/EditPage/EditPage.jsx
  src/pages/PostPage/PostIdPage/PostIdPage.jsx
  src/pages/PostPage/PostIdPage/PostIdPage.module.scss
  src/pages/PostPage/PostPage.jsx
Labels: ⏳ PR 머지 대기 중

#67 [feat] message page
  src/assets/images/logo.svg
  src/assets/images/plus.svg
  src/components/Dropdown/Dropdown.jsx
  src/components/Dropdown/Dropdown.module.scss
  src/components/Header/HeaderComponents/Header.jsx
  src/components/Header/HeaderComponents/HeaderService.jsx
  src/components/Input/InputText.module.scss
  src/components/ProfileImg/ProfileImg.jsx
  src/components/ProfileImg/ProfileImg.module.scss
  src/components/ServiceSection/ServiceSection.jsx
  src/components/TextEditor/TextEditor.module.scss
  src/hooks/useGetProfileImg.js
  src/pages/HomePage/HomePage.jsx
  src/pages/ListPage/ListPage.jsx
  src/pages/ListPage/ListPage.module.scss
  src/pages/PostPage/PostIdPage/MessagePage/MessagePage.jsx
  src/pages/PostPage/PostIdPage/MessagePage/MessagePage.module.scss
Labels: ⏳ PR 머지 대기 중
